swagger: "2.0"
info:
  title: "Book Management API"
  description: "API for managing books."
  version: "1.0.0"
host: "localhost:5000"
schemes:
  - "http"
paths:
  /books:
    get:
      summary: "Get all books"
      responses:
        200:
          description: "A list of books"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Book"
    post:
      summary: "Create a new book"
      parameters:
        - in: "body"
          name: "book"
          description: "Book to add"
          required: true
          schema:
            $ref: "#/definitions/Book"
      responses:
        201:
          description: "Book created"
  /books/{book_id}:
    get:
      summary: "Get a book by ID"
      parameters:
        - in: "path"
          name: "book_id"
          required: true
          type: "string"
      responses:
        200:
          description: "A single book"
          schema:
            $ref: "#/definitions/Book"
    put:
      summary: "Update a book by ID"
      parameters:
        - in: "path"
          name: "book_id"
          required: true
          type: "string"
        - in: "body"
          name: "book"
          description: "Book data to update"
          schema:
            $ref: "#/definitions/Book"
      responses:
        200:
          description: "Book updated"
    delete:
      summary: "Delete a book by ID"
      parameters:
        - in: "path"
          name: "book_id"
          required: true
          type: "string"
      responses:
        200:
          description: "Book deleted"
definitions:
  Book:
    type: "object"
    properties:
      title:
        type: "string"
      author:
        type: "string"
      published_date:
        type: "string"
